swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Sulam"
host: "140.82.55.136"
paths:
  /glogin:
    post:
      tags:
      - "glogin"
      summary: "Creates or update an user and send a JWT"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "400":
          description: "Could not create or update the user"
          schema:
            $ref: "#/definitions/Error"
        "200":
          description: "User created or updated successfully"
          schema:
            $ref: "#/definitions/GooglinResponse"
definitions:
  User:
    type: "object"
    properties:
      googleId:
        type: "string"
      lastLogin:
        type: "string"
      email:
        type: "string"
      name:
        type: "string"
  GooglinResponse:
    type: "object"
    properties:
      success:
        type: "boolean"
      message:
        type: "string"
      data:
        type: "object"
        properties:
          token:
            type: "string"
  Error:
    type: "object"
    properties:
      message:
        type: "string"
      description:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"