swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Sulam"
host: "140.82.55.136"
paths:
  /glogin:
    post:
      tags:
      - "glogin"
      summary: "Creates or update an user and send a JWT"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "400":
          description: "Could not create or update the user"
          schema:
            $ref: "#/definitions/Error"
        "200":
          description: "User created or updated successfully"
          schema:
            $ref: "#/definitions/GooglinResponse"
  /library:
    get:
      tags:
      - "library"
      summary: "Get all books with its lessons"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "400":
          description: "Could not get all books'"
          schema:
            $ref: "#/definitions/Error"
        "200":
          description: "All books returned successfully"
          schema:
            $ref: "#/definitions/LibraryResponse"
  /savePage:
    post:
      tags:
      - "savePage"
      summary: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "SavePageRequest"
          required: true
          schema:
            $ref: "#/definitions/SavePageRequest"
      responses:
        "400":
          description: ""
          schema:
            $ref: "#/definitions/Error"
        "200":
          description: "All books returned successfully" 
          schema:
            $ref: "#/definitions/CommonResponse"
  /favorite:
    post:
      tags:
      - "favorite"
      summary: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "FavoriteRequest"
          required: true
          schema:
            $ref: "#/definitions/FavoriteRequest"
      responses:
        "400":
          description: ""
          schema:
            $ref: "#/definitions/Error"
        "200":
          description: "All books returned successfully"
          schema:
            $ref: "#/definitions/CommonResponse"
  /contactUs:
    post:
      tags:
      - "contactUs"
      summary: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "ContactUsRequest"
          required: true
          schema:
            $ref: "#/definitions/ContactUsRequest"
      responses:
        "400":
          description: ""
          schema:
            $ref: "#/definitions/Error"
        "200":
          description: "All books returned successfully"
          schema:
            $ref: "#/definitions/CommonResponse"
definitions:
  User:
    type: "object"
    properties:
      googleId:
        type: "string"
      lastLogin:
        type: "string"
      email:
        type: "string"
      name:
        type: "string"
  SavePageRequest:
    type: "object"
    properties:
      lessonId:
        type: "number"
      lastPage:
        type: "string"
      timestamp:
        type: "string"
      userId:
        type: "string"
  ContactUsRequest:
    type: "object"
    properties:
      text:
        type: "string"
      timestamp:
        type: "string"
      userId:
        type: "number"
  FavoriteRequest:
    type: "object"
    properties:
      bookId:
        type: "number"
      favorite:
        type: "string"
      timestamp:
        type: "string"
      userId:
        type: "number"
  GooglinResponse:
    type: "object"
    properties:
      success:
        type: "boolean"
      message:
        type: "string"
      data:
        type: "object"
        properties:
          token:
            type: "string"
  CommonResponse:
    type: "object"
    properties:
      success:
        type: "boolean"
      message:
        type: "string"
      data:
        type: "string"
  LibraryResponse:
    type: "object"
    properties:
      success:
        type: "boolean"
      message:
        type: "string"
      data:
        type: "object"
        properties:
          id:
            type: "number"
          name:
            type: "string"
          favorite:
            type: "boolean"
          lessons:
            type: "array"
            items:
              type: "object"
              properties: 
                id:
                  type: "number"
                pdfPath:
                  type: "string"
                urlPath:
                  type: "string"
                name:
                  type: "string"
                picture:
                  type: "string"
                dateAdded:
                  type: "string"
                numberOfPages:
                  type: "string"
  Error:
    type: "object"
    properties:
      message:
        type: "string"
      description:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"